from typing import Protocol, Callable
from dex_hand.core.observation import CanonicalObservation


class HandAdapter(Protocol):
    dt: float
    # Shared local runtime metadata, independent of embodiment identifiers.
    active_modes: list[str]
    events: list[dict]
    last_command: dict
    skill: str
    phase: str
    grasp_verified: bool
    verified_groups: tuple[str, ...]
    verified_reference: object
    def get_capabilities(self) -> dict: ...
    def get_observation_capabilities(self) -> dict: ...
    def read_raw_state(self) -> dict: ...
    def build_canonical_observation(self) -> CanonicalObservation: ...
    def get_joint_positions(self): ...
    def get_joint_velocities(self): ...
    def get_joint_efforts(self): ...
    def command_joint_positions(self, positions): ...
    def command_joint_targets(self, targets): ...
    def command_actuators(self, command): ...
    def get_contact_groups(self): ...
    def resolve_contact_group(self, group): ...
    def get_contact_group_pose(self, group): ...
    def prepare_configuration(self, profile, object_id, groups, aperture, clearance): ...
    def configuration_error(self) -> float: ...
    def advance_groups(self, object_id, groups, distances): ...
    def safe_hold(self): ...
    def add_step_callback(self, callback: Callable): ...
    def remove_step_callback(self, callback: Callable): ...
    def step(self, steps: int = 1): ...
